[project]
name = "cli-ticket-rpg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "art>=6.5",
    "textual>=6.0.0",
    "textual-dev>=1.7.0",
]
